require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# be a bit kinder with our metrics
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

Layout/LineLength:
  Max: 120
